# https://docs.docker.com/compose/how-tos/multiple-compose-files/include/#include-and-overrides
services:
  php:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`)"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"
      # HTTPS config - uncomment to enable redirect from :80 to :443
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  # scorpio:
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.docker.network=frontend"
  #     - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_scorpio.rule=Host(`scorpio.${COMPOSE_DOMAIN}`)"
  #     - "traefik.http.services.${COMPOSE_PROJECT_NAME}_scorpio.loadbalancer.server.port=9090"
  #     # HTTPS config - uncomment to enable redirect from :80 to :443
  #     - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_scorpio.middlewares=redirect-to-https"
  #     - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  idm:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_idm.rule=Host(`idm.${COMPOSE_DOMAIN}`)"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}_idm.loadbalancer.server.port=3000"
      # HTTPS config - uncomment to enable redirect from :80 to :443
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_idm.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  pep-proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_pep-proxy.rule=Host(`pep-proxy.${COMPOSE_DOMAIN}`)"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}_pep-proxy.loadbalancer.server.port=80"
      # HTTPS config - uncomment to enable redirect from :80 to :443
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_pep-proxy.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
